title: Qi She (佘琪)'s website
author: Qi She
email: sheqi1991@gmail.com
url: "https://sheqi.github.io"
description: > # this means to ignore newlines until "show_exerpts:"
  Qi She, Research Scientist, machine learning, deep learning, computer vision, robotics, artificial intelligence
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Qi She (佘琪)
  tagline: false
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/img/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
  navigation:
    - title: Homepage
      url: "/index"
    - title: Publication
      url: "/publication"
    - title: About me
      url: "/aboutme"
    - title: Blog
      url: https://qishe.wordpress.com/
    #- title: CV
    #  url: "/cv"
  # generate social links in footer
  social_links:
    researchgate: profile/Qi-She-3
    #github:  sheqi
    linkedIn: in/qi-she-57ab259a
    #twitter: sheqi1991
  analytics_id: "G-G9J3D02VP5"
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
